storage:
  ova:
    repository: https://files.techno-cyber-lab.store
    store_to: ./ova
  virtual_machines:
    store_to: ./vms

virtual_machines:
  - name: firewall-1
    ova_filename: fw1-pfsense.ova
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: firewall-2
    ova_filename: fw2-pfsense.ova
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: web-server
    ova_filename: dmz-serv.ova
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: database-server
    ova_filename: db-serv.ova
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: wan-client
    ova_filename: kali-client.ova
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton

  - name: lan-client
    ova_filename: kali-lan-client.ova
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton