storage:
  repository: https://files.techno-cyber-lab.store
  ova_store_to: './ova'
  vms_store_to: './vms'
  import_log_store_to: "./import_log"

virtual_machines:
  - name: firewall-1
    ova_filename: firewall-1-001.ova
    md5checksum: 90c2b8ad4f63c7dc9e67c033f17d2051
    nics:
      - nic_index: 1
        type: natnetwork
        network_name: cyberlab
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: firewall-2
    ova_filename: firewall-2-001.ova
    md5checksum: 84dee64515c4cc82ad79d0d1c433fbf3
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: web-server
    ova_filename: web-server-001.ova
    md5checksum: 8e6f5eb76c464cec70fc9cdaccc84f4e
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: database-server
    ova_filename: database-server-001.ova
    md5checksum: 524125bfa0241fd63ea09ee3c83801c3
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: wan-client
    ova_filename: wan-client-001.ova
    md5checksum: 483f69ced2c1cff47e65e7984077adfd
    nics:
      - nic_index: 1
        type: natnetwork
        network_name: cyberlab
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton

  - name: lan-client
    ova_filename: lan-client-001.ova
    md5checksum: 0d279be6454d75f8ec08fffcb7c130cb
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton