virtual_machines:
  - name: firewall-1
    ova_url: https://files.techno-cyber-lab.store/fw1-pfsense.ova
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: firewall-2
    ova_url: https://files.techno-cyber-lab.store/fw2-pfsense.ova
    boot_policy:
      startup: headless
      shutdown: savestate

  - name: web-server
    ova_url: https://files.techno-cyber-lab.store/dmz-serv.ova
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: database-server
    ova_url: https://files.techno-cyber-lab.store/db-serv.ova
    boot_policy:
      startup: headless
      shutdown: acpipowerbutton

  - name: wan-client
    ova_url: https://files.techno-cyber-lab.store/kali-client.ova
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton

  - name: lan-client
    ova_url: https://files.techno-cyber-lab.store/kali-lan-client.ova
    boot_policy:
      startup: gui
      shutdown: acpipowerbutton